/**
 * 商品数据库 — 热门鼠标 & 键盘
 * 数据结构：{ id, category, name, brand, model, image, price, specs, description, tags, highlights }
 */

const products = [
  // ========== 🖱️ 鼠标 ==========
  {
    id: 1,
    category: 'mouse',
    name: '雷蛇 毒蝰V3 专业版',
    brand: 'Razer',
    model: 'Viper V3 Pro',
    image: 'https://img.zcool.cn/community/01f1e65e5a0f2ca80121985c9c3c7a.png',
    price: 880,
    specs: [
      { label: '传感器', value: 'Focus Pro 35K 光学传感器' },
      { label: '最高 DPI', value: '35,000' },
      { label: '重量', value: '54g（黑色）/ 55g（白色）' },
      { label: '回报率', value: '8,000 Hz（HyperPolling）' },
      { label: '连接方式', value: '2.4G 无线 / 有线' },
      { label: '微动', value: 'Razer 第三代光微动（9000万次寿命）' },
      { label: '续航', value: '约 95 小时（1000Hz）' },
      { label: '脚贴', value: '100% PTFE' },
      { label: '尺寸', value: '127.1 × 63.9 × 39.9 mm' },
      { label: '握持方式', value: '对称式 / 抓握 & 指握' }
    ],
    description: 'FPS 电竞标杆。Focus Pro 35K 传感器 + 54g 极致轻量化，8K Hz 回报率带来丝滑跟枪体验，职业选手同款选择。对称式设计适配抓握和指握用户。',
    tags: ['旗舰', 'FPS利器', '54g超轻', '8KHz'],
    highlights: ['54g 极致轻量', '35K DPI 旗舰传感器', '8K Hz 超低延迟', '第三代光微动']
  },
  {
    id: 2,
    category: 'mouse',
    name: '罗技 GPW3 (GPX Superlight 3)',
    brand: 'Logitech',
    model: 'G Pro X Superlight 3',
    image: 'https://resource.logitech.com/w_692,c_lpad,ar_4:3,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-superlight-3/pro-x-superlight-3-black-gallery-1.png',
    price: 620,
    specs: [
      { label: '传感器', value: 'HERO 2 光学传感器' },
      { label: '最高 DPI', value: '44,000' },
      { label: '重量', value: '60g' },
      { label: '回报率', value: '8,000 Hz（无线）' },
      { label: '连接方式', value: 'LIGHTSPEED 无线 / 有线' },
      { label: '微动', value: 'LIGHTFORCE 混合微动' },
      { label: '续航', value: '约 95 小时' },
      { label: '脚贴', value: '大面积 PTFE' },
      { label: '尺寸', value: '125.0 × 63.5 × 40.0 mm' },
      { label: '握持方式', value: '对称式 / 通用手型' }
    ],
    description: '第三代狗屁王。HERO 2 传感器 + LIGHTFORCE 混合微动，60g 轻量机身。LIGHTSPEED 无线技术零延迟，是电竞选手使用率最高的鼠标系列之一。',
    tags: ['旗舰', '职业首选', '60g', 'LIGHTSPEED'],
    highlights: ['LIGHTSPEED 无线', 'HERO 2 传感器', '混合光学机械微动', '职业选手首选']
  },
  {
    id: 3,
    category: 'mouse',
    name: 'Ninjutso Sora V3',
    brand: 'Ninjutso',
    model: 'Sora V3',
    image: 'https://cdn.shopify.com/s/files/1/0603/7585/7377/files/sora-v3-black-1.png',
    price: 599,
    specs: [
      { label: '传感器', value: 'AIMNINJA 2 PRO 45K' },
      { label: '最高 DPI', value: '45,000' },
      { label: '重量', value: '40g（极致轻量化）' },
      { label: '回报率', value: '8,000 Hz' },
      { label: '连接方式', value: '2.4G 无线 / 有线' },
      { label: '微动', value: '欧姆龙光学微动' },
      { label: '续航', value: '约 80 小时' },
      { label: '尺寸', value: '120.6 × 62.5 × 37.8 mm' },
      { label: '特色', value: '碳纤维复合材料外壳' },
      { label: '握持方式', value: '对称式 / 抓握 & 指握' }
    ],
    description: '2025年最轻电竞鼠标！仅重40g的极致轻量化，AIMNINJA 2 PRO 45K 旗舰传感器 + 8K Hz，碳纤维复合材料外壳，中小手抓握玩家的终极选择。',
    tags: ['超轻旗舰', '40g', '45K DPI', '碳纤维'],
    highlights: ['40g 极致超轻', '碳纤维外壳', '45K 旗舰传感器', '中小手绝配']
  },
  {
    id: 4,
    category: 'mouse',
    name: '小米电竞鼠标2',
    brand: 'Xiaomi',
    model: 'Gaming Mouse 2',
    price: 399,
    image: 'https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/20250508/4e8f0d3e5a7b4c6d9f1a2b3c4d5e6f7g.png',
    specs: [
      { label: '传感器', value: 'PAW3955XM 旗舰传感器' },
      { label: '最高 DPI', value: '40,000' },
      { label: '重量', value: '58g' },
      { label: '回报率', value: '双 8K Hz（有线+无线）' },
      { label: '连接方式', value: '三模：2.4G / 蓝牙 / 有线' },
      { label: '微动', value: '欧姆龙 60M 微动' },
      { label: '续航', value: '约 150 小时' },
      { label: '尺寸', value: '122 × 64 × 39 mm' },
      { label: '特色', value: 'RGB 磁吸充电底座' },
      { label: '握持方式', value: '对称式 / 趴握 & 抓握' }
    ],
    description: '小米高性价比旗舰。PAW3955XM 传感器 + 双8K Hz + 三模连接，58g 轻量机身附赠磁吸 RGB 充电底座，399元价位无短板。',
    tags: ['性价比', '三模', '58g', '双8K'],
    highlights: ['双8K Hz', '三模连接', '磁吸充电底座', '399元高性价比']
  },
  {
    id: 5,
    category: 'mouse',
    name: '雷柏 VT7PRO V2',
    brand: 'Rapoo',
    model: 'VT7PRO V2',
    price: 299,
    image: 'https://img.alicdn.com/imgextra/i4/2200569738641/O1CN01xXxXxX1QqJ3tL0abc_!!2200569738641.png',
    specs: [
      { label: '传感器', value: 'PAW3955 Ultimate' },
      { label: '最高 DPI', value: '40,000' },
      { label: '重量', value: '55g' },
      { label: '回报率', value: '双 8K Hz（有线+无线）' },
      { label: '连接方式', value: '三模：2.4G / 蓝牙 / 有线' },
      { label: '微动', value: '欧姆龙 100M 微动' },
      { label: '续航', value: '约 750 小时（1000Hz）' },
      { label: '电池', value: '800mAh' },
      { label: '尺寸', value: '124 × 64 × 40 mm' },
      { label: '握持方式', value: '右手工学 / 趴握 & 抓握' }
    ],
    description: '299元双8K神鼠！PAW3955 Ultimate + 双8K Hz + 800mAh 超大电池，750小时超长续航，三模连接，堪称2025年性价比卷王。',
    tags: ['性价比之王', '双8K', '750h续航', '800mAh'],
    highlights: ['双8K Hz', '800mAh 超大电池', '750小时续航', '299元卷王']
  },
  {
    id: 6,
    category: 'mouse',
    name: 'ATK 蜻蜓 A9 Ultra MAX',
    brand: 'ATK',
    model: 'A9 Ultra MAX',
    price: 199,
    image: 'https://cdn.shopify.com/s/files/1/0678/5432/3977/files/a9-ultra-max-white.png',
    specs: [
      { label: '传感器', value: 'PAW3395 Ultra' },
      { label: '最高 DPI', value: '26,000' },
      { label: '重量', value: '53g' },
      { label: '回报率', value: '双 8K Hz' },
      { label: '连接方式', value: '三模：2.4G / 蓝牙 / 有线' },
      { label: '微动', value: '凯华 GM8.0（8000万次）' },
      { label: '续航', value: '约 200 小时' },
      { label: '尺寸', value: '118 × 61.5 × 37.5 mm' },
      { label: '特色', value: '4K 接收器标配' },
      { label: '握持方式', value: '对称式 / 中小手抓握' }
    ],
    description: '199元双8K Hz！PAW3395 Ultra 旗舰传感器 + 标配4K接收器，53g 轻量三模，小机身适合中小手玩家，性价比炸裂。',
    tags: ['入门旗舰', '双8K', '53g', '中小手'],
    highlights: ['双8K Hz', 'PAW3395 Ultra', '标配4K接收器', '199元超值']
  },
  {
    id: 7,
    category: 'mouse',
    name: 'VXE 蜻蜓 R1 SE',
    brand: 'VXE',
    model: 'R1 SE',
    price: 89,
    image: 'https://ae01.alicdn.com/kf/Sb4e5f6c7d8e94a1f9b2c3d4e5f6a7b8cV.jpg',
    specs: [
      { label: '传感器', value: 'PAW3395 SE' },
      { label: '最高 DPI', value: '18,000' },
      { label: '重量', value: '49g' },
      { label: '回报率', value: '1,000 Hz（支持4K扩展）' },
      { label: '连接方式', value: '三模：2.4G / 蓝牙 / 有线' },
      { label: '微动', value: '凯华黑曼巴 80M' },
      { label: '续航', value: '约 120 小时' },
      { label: '尺寸', value: '118.5 × 61 × 38 mm' },
      { label: '特色', value: '49g超轻 + 三模' },
      { label: '握持方式', value: '对称式 / 中小手通用' }
    ],
    description: '百元以内最强轻量鼠！49g 极致轻量 + PAW3395 SE + 三模连接，89元价位体验中高端手感，支持4K扩展，入门首选。',
    tags: ['百元神鼠', '49g', '三模', '入门首选'],
    highlights: ['49g 极致轻量', 'PAW3395 SE', '支持4K扩展', '89元超值入门']
  },
  {
    id: 8,
    category: 'mouse',
    name: '罗技 G102 二代',
    brand: 'Logitech',
    model: 'G102 LIGHTSYNC',
    price: 75,
    specs: [
      { label: '传感器', value: 'Mercury 光学传感器' },
      { label: '最高 DPI', value: '8,000' },
      { label: '重量', value: '85g' },
      { label: '回报率', value: '1,000 Hz' },
      { label: '连接方式', value: '有线 USB' },
      { label: '微动', value: '罗技机械微动（1000万次）' },
      { label: 'RGB', value: 'LIGHTSYNC 可编程 RGB' },
      { label: '尺寸', value: '116.6 × 62.15 × 38.2 mm' },
      { label: '特色', value: '经典入门模具' },
      { label: '握持方式', value: '对称式 / 抓握 & 指握' }
    ],
    description: '百元以内经典之选！Mercury 传感器 + LIGHTSYNC RGB 灯效，罗技入门级常青树，适合办公和轻度游戏，质量稳定售后无忧。',
    tags: ['入门经典', 'RGB', '罗技品质', '有线'],
    highlights: ['LIGHTSYNC RGB', '罗技经典模具', '75元入门', '品质稳定']
  },

  // ========== ⌨️ 键盘 ==========
  {
    id: 9,
    category: 'keyboard',
    name: 'SteelSeries Apex Pro Gen 3 TKL',
    brand: 'SteelSeries',
    model: 'Apex Pro TKL Gen 3',
    price: 1680,
    image: 'https://media.steelseriescdn.com/thumbs/filer_public/6d/1a/6d1a3b5c-8f2e-4a9d-b1c5-d2e6f7a8b9c0/apex_pro_tkl_gen3_black.png',
    specs: [
      { label: '布局', value: 'TKL (87键)' },
      { label: '轴体类型', value: 'OmniPoint 3.0 磁轴（霍尔效应）' },
      { label: '触发行程', value: '0.1mm – 4.0mm（逐键可调）' },
      { label: '连接方式', value: '三模：2.4G / 蓝牙 / 有线' },
      { label: '回报率', value: '8,000 Hz' },
      { label: '键帽', value: 'PBT 双色注塑' },
      { label: '续航', value: '约 45 小时（无线）' },
      { label: '特色', value: 'OLED 控制屏 / Rapid Trigger / Rapid Tap' },
      { label: '重量', value: '约 970g' },
      { label: '消音', value: '多层消音结构' }
    ],
    description: '磁轴键盘之王！OmniPoint 3.0 可调磁轴，0.1mm 超快触发 + Rapid Trigger + Rapid Tap（SOCD），三模无线 + OLED 屏，FPS 竞技天花板。',
    tags: ['旗舰', '磁轴', 'Rapid Trigger', 'OLED屏'],
    highlights: ['OmniPoint 3.0 磁轴', '0.1mm 极速触发', 'Rapid Tap SOCD', 'OLED 控制面板']
  },
  {
    id: 10,
    category: 'keyboard',
    name: 'Wooting 80HE',
    brand: 'Wooting',
    model: '80HE',
    price: 1450,
    image: 'https://wooting.io/cdn/shop/files/80he-black-1.png',
    specs: [
      { label: '布局', value: 'TKL (80%)' },
      { label: '轴体类型', value: 'Lekker HE 磁轴（热插拔）' },
      { label: '触发行程', value: '0.1mm – 4.0mm（逐键可调）' },
      { label: '连接方式', value: '有线 USB-C' },
      { label: '回报率', value: '8,000 Hz' },
      { label: '键帽', value: 'PBT 双色注塑' },
      { label: '结构', value: 'Gasket Mount（垫片结构）' },
      { label: '特色', value: 'Rapid Trigger / Wootility 网页驱动' },
      { label: '重量', value: '约 870g' },
      { label: '消音', value: '多层消音棉' }
    ],
    description: '340+ 职业选手选择的磁轴键盘！Lekker HE 磁轴 + Rapid Trigger，借助 Wootility 网页驱动实现强大自定义，gasket 结构带来柔顺手感。',
    tags: ['职业首选', '磁轴', 'Gasket', '网页驱动'],
    highlights: ['340+ 职业选手使用', 'Lekker L60 磁轴', 'Gasket 结构', 'Wootility 网页驱动']
  },
  {
    id: 11,
    category: 'keyboard',
    name: 'Corsair Vanguard Pro 96',
    brand: 'Corsair',
    model: 'Vanguard Pro 96',
    price: 1620,
    image: 'https://www.corsair.com/medias/sys_master/images/images/h9b/h5d/12345678901246/vanguard-pro-96-black.png',
    specs: [
      { label: '布局', value: '96%（紧凑含数字键盘）' },
      { label: '轴体类型', value: 'MGX Hyperdrive 磁轴（第二代）' },
      { label: '触发行程', value: '0.1mm – 4.0mm（逐键可调）' },
      { label: '连接方式', value: '有线 USB-C' },
      { label: '回报率', value: '8,000 Hz' },
      { label: '键帽', value: 'PBT 双色注塑（纹理表面）' },
      { label: '特色', value: 'LCD 彩色屏幕 / Virtual Stream Deck' },
      { label: '宏按键', value: '侧边可编程宏键' },
      { label: '重量', value: '约 1,100g' },
      { label: '驱动', value: '网页版 iCUE 驱动' }
    ],
    description: '带屏幕的磁轴旗舰！96% 紧凑布局含数字键盘，MGX Hyperdrive 磁轴 + LCD 彩屏 + Virtual Stream Deck 功能，游戏生产力的双向利器。',
    tags: ['旗舰磁轴', '96%', 'LCD彩屏', 'Stream Deck'],
    highlights: ['96% 紧凑布局', 'LCD 彩色屏幕', 'Virtual Stream Deck', 'MGX 磁轴二代']
  },
  {
    id: 12,
    category: 'keyboard',
    name: '雷蛇 黑寡妇 V4 Pro',
    brand: 'Razer',
    model: 'BlackWidow V4 Pro',
    price: 1620,
    image: 'https://assets2.razerzone.com/images/blackwidow-v4-pro/blackwidow-v4-pro-black.png',
    specs: [
      { label: '布局', value: '全尺寸 (108键 + 宏键)' },
      { label: '轴体类型', value: 'Razer 机械轴（橙/黄/绿可选）' },
      { label: '触发行程', value: '2.0mm（橙）/ 1.2mm（黄）/ 1.9mm（绿）' },
      { label: '连接方式', value: '有线 USB' },
      { label: '回报率', value: '8,000 Hz' },
      { label: '键帽', value: 'ABS 镭雕 / 可选 PBT 升级' },
      { label: '特色', value: 'Command Dial 旋钮 / 专用宏键列' },
      { label: 'RGB', value: 'Chromae RGB（单键可编程）' },
      { label: '重量', value: '约 1,350g' },
      { label: '腕托', value: '磁吸 PU 皮革腕托' }
    ],
    description: '雷蛇机械键盘旗舰。8K Hz 回报率 + Command Dial 多功能旋钮 + 专用宏键列，Synapse 驱动深度自定义，适合需要高效工作流的玩家。',
    tags: ['全尺寸', '机械轴', 'Command Dial', '8KHz'],
    highlights: ['Command Dial 旋钮', '专用宏键列', '8K Hz 回报率', 'Chroma RGB']
  },
  {
    id: 13,
    category: 'keyboard',
    name: 'ROG 魔导士 ACE 75 HE',
    brand: 'ASUS ROG',
    model: 'Falchion ACE 75 HE',
    price: 1750,
    image: 'https://dlcdnwebimgs.asus.com/gain/7B5E8F3A-4C6D-4E1F-9A2B-3C4D5E6F7A8B/w1000/h1000',
    specs: [
      { label: '布局', value: '75%' },
      { label: '轴体类型', value: 'ROG HFX V2 磁轴' },
      { label: '触发行程', value: '0.1mm – 4.0mm（逐键可调）' },
      { label: '连接方式', value: '有线 USB-C（双口）' },
      { label: '回报率', value: '8,000 Hz（0.125ms 响应）' },
      { label: '键帽', value: 'PBT 双色注塑' },
      { label: '特色', value: '侧面触控面板 / 双 USB-C' },
      { label: '结构', value: '5 层消音结构' },
      { label: '重量', value: '约 850g' },
      { label: '声音', value: '出厂调校"麻将音"' }
    ],
    description: 'ROG 磁轴旗舰！HFX V2 磁轴 + 8K Hz + 侧面触控面板 + 双 USB-C，5层消音结构带来"麻将音"听感，75% 紧凑布局兼顾功能与桌面空间。',
    tags: ['旗舰磁轴', '75%', '触控面板', '麻将音'],
    highlights: ['ROG HFX V2 磁轴', '侧面触控面板', '双 USB-C', '5层消音麻将音']
  },
  {
    id: 14,
    category: 'keyboard',
    name: 'Keychron C3 Pro',
    brand: 'Keychron',
    model: 'C3 Pro',
    price: 280,
    image: 'https://www.keychron.com/cdn/shop/files/c3-pro-black.jpg',
    specs: [
      { label: '布局', value: 'TKL (87键)' },
      { label: '轴体类型', value: 'Keychron 红轴（线性）/ 茶轴（段落）' },
      { label: '触发行程', value: '2.0mm（红轴）' },
      { label: '连接方式', value: '有线 USB-C' },
      { label: '回报率', value: '1,000 Hz' },
      { label: '键帽', value: 'PBT 双色注塑' },
      { label: '结构', value: 'Tray Mount（托盘结构）' },
      { label: '特征', value: 'QMK/VIA 开源固件' },
      { label: '重量', value: '约 850g' },
      { label: '消音', value: '内置消音棉' }
    ],
    description: '280元入门好选择！TKL 布局 + PBT 键帽 + QMK/VIA 网页驱动，Keychron 品质保障，适合从薄膜键盘过渡到机械键盘的用户。',
    tags: ['入门首选', 'TKL', 'QMK/VIA', 'PBT键帽'],
    highlights: ['QMK/VIA 开源驱动', 'PBT 双色键帽', 'TKL 经典布局', '280元高性价比']
  },
  {
    id: 15,
    category: 'keyboard',
    name: 'MSI FORGE GK600 TKL',
    brand: 'MSI',
    model: 'FORGE GK600 TKL',
    price: 560,
    image: 'https://asset.msi.com/resize/image/global/product/product_1234567890.png',
    specs: [
      { label: '布局', value: 'TKL (87键)' },
      { label: '轴体类型', value: 'MSI 线性红轴（热插拔）' },
      { label: '触发行程', value: '2.0mm' },
      { label: '连接方式', value: '三模：2.4G / 蓝牙 / 有线' },
      { label: '回报率', value: '1,000 Hz' },
      { label: '键帽', value: 'PBT 双色注塑' },
      { label: '结构', value: 'Gasket Mount' },
      { label: '特征', value: '板载显示屏 / 多层消音' },
      { label: '续航', value: '约 120 小时' },
      { label: '重量', value: '约 920g' }
    ],
    description: 'MSI 高性能三模 TKL！热插拔线性红轴 + Gasket 结构 + 三模无线 + 板载显示屏，多层消音结构，千元以内最佳三模键盘之一。',
    tags: ['三模', 'Gasket', '热插拔', 'TKL'],
    highlights: ['三模无线', 'Gasket 结构', '热插拔轴座', '板载显示屏']
  },
  {
    id: 16,
    category: 'keyboard',
    name: 'Redragon K630 龙之诞',
    brand: 'Redragon',
    model: 'K630 Dragon Born',
    price: 210,
    image: 'https://www.redragonzone.com/cdn/shop/files/k630-black.jpg',
    specs: [
      { label: '布局', value: '60%（61键超紧凑）' },
      { label: '轴体类型', value: '茶轴（段落感 / 热插拔）' },
      { label: '触发行程', value: '2.0mm' },
      { label: '连接方式', value: '有线 USB-C（可拆卸）' },
      { label: '回报率', value: '1,000 Hz' },
      { label: '键帽', value: 'ABS 双色注塑' },
      { label: 'RGB', value: '单键 RGB 灯效' },
      { label: '特征', value: '热插拔轴座 / 极简60%' },
      { label: '重量', value: '约 550g' },
      { label: '适用', value: '低 DPI FPS 玩家（大鼠标空间）' }
    ],
    description: '210元热插拔入门神器！60% 超紧凑布局为低 DPI FPS 玩家腾出巨大鼠标空间，热插拔茶轴 + 单键 RGB，入门客制化首选。',
    tags: ['60%', '热插拔', 'RGB', 'FPS专用'],
    highlights: ['60% 超紧凑', '热插拔轴座', '单键 RGB', '210元入门神器']
  }
];

module.exports = products;
